FLPTools Development: optasio::flp::RationalExpr Class Reference
optasio::flp::RationalExpr Class Reference
#include <rational_expr.hpp>
Public Member Functions
RationalExpr (LinearExpr enumerator=1, LinearExpr denominator=1)
bool is_valid () const
bool is_linear () const
RationalExpr & operator+= (double rhs)
RationalExpr & operator-= (double rhs)
RationalExpr & operator*= (double rhs)
RationalExpr & operator/= (double rhs)
RationalExpr operator- () const
Public Attributes
LinearExpr enumerator { 1 }
LinearExpr denominator { 1 }
Detailed Description
Definition at line 13 of file rational_expr.hpp.
Constructor & Destructor Documentation
RationalExpr()
optasio::flp::RationalExpr::RationalExpr (LinearExpr enumerator = 1, LinearExpr denominator = 1) inline
Definition at line 18 of file rational_expr.hpp.
References denominator, enumerator, is_linear(), is_valid(), optasio::flp::operator*(), operator*=(), optasio::flp::operator+(), operator+=(), operator-(), operator-=(), operations_research::operator/(), and operator/=().
Referenced by operations_research::operator/().
     : enumerator(enumerator), denominator(denominator)
   {}
Member Function Documentation
is_linear()
bool optasio::flp::RationalExpr::is_linear () const
Definition at line 18 of file rational_expr.cpp.
References denominator.
Referenced by RationalExpr(), and TEST().
{
   bool all_coeffs_are_zero = denominator.terms().size() == 0;
   return denominator.offset() != 0 && all_coeffs_are_zero;
 }
is_valid()
bool optasio::flp::RationalExpr::is_valid () const
Definition at line 14 of file rational_expr.cpp.
References denominator, and optasio::flp::linear_expr_is_nonzero().
Referenced by RationalExpr(), and TEST().
{
   return linear_expr_is_nonzero(denominator);
 }
operator*=()
RationalExpr & optasio::flp::RationalExpr::operator*= (double rhs)
Definition at line 33 of file rational_expr.cpp.
References enumerator.
Referenced by RationalExpr().
{
   enumerator *= rhs;
   return *this;
 }
operator+=()
RationalExpr & optasio::flp::RationalExpr::operator+= (double rhs)
Definition at line 23 of file rational_expr.cpp.
References denominator, and enumerator.
Referenced by RationalExpr().
{
   enumerator += rhs * denominator;
   return *this;
 }
operator-()
RationalExpr optasio::flp::RationalExpr::operator- () const
Definition at line 44 of file rational_expr.cpp.
Referenced by RationalExpr().
{
   return -1 * (*this);
 }
operator-=()
RationalExpr & optasio::flp::RationalExpr::operator-= (double rhs)
Definition at line 28 of file rational_expr.cpp.
References denominator, and enumerator.
Referenced by RationalExpr().
{
   enumerator -= rhs * denominator;
   return *this;
 }
operator/=()
RationalExpr & optasio::flp::RationalExpr::operator/= (double rhs)
Definition at line 38 of file rational_expr.cpp.
References denominator.
Referenced by RationalExpr().
{
   DCHECK_NE(rhs, 0);
   denominator *= rhs;
   return *this;
 }
Member Data Documentation
denominator
LinearExpr optasio::flp::RationalExpr::denominator { 1 }
Definition at line 16 of file rational_expr.hpp.
Referenced by is_linear(), is_valid(), operator+=(), operator-=(), operator/=(), RationalExpr(), and TEST().
enumerator
LinearExpr optasio::flp::RationalExpr::enumerator { 1 }
Definition at line 15 of file rational_expr.hpp.
Referenced by operator*=(), operator+=(), operator-=(), RationalExpr(), and TEST().
The documentation for this class was generated from the following files:
/datadisk/bbubu/repos/optasio/flp-tools/src/rational_expr.hpp
/datadisk/bbubu/repos/optasio/flp-tools/src/rational_expr.cpp