FLPTools Development: optasio::flp::FLPSolver Class Reference
optasio::flp::FLPSolver Class Reference
#include <flp_solver.hpp>
Public Member Functions
FLPSolver (const std::string &name, OptimizationProblemType type=OptimizationProblemType::SCIP_MIXED_INTEGER_PROGRAMMING)
std::string message () const
Detailed Description
Definition at line 13 of file flp_solver.hpp.
Constructor & Destructor Documentation
FLPSolver()
optasio::flp::FLPSolver::FLPSolver (const std::string & name, OptimizationProblemType type = OptimizationProblemType::SCIP_MIXED_INTEGER_PROGRAMMING) inline
Definition at line 15 of file flp_solver.hpp.
References message().
     : MPSolver(name, type) {}
Member Function Documentation
message()
std::string optasio::flp::FLPSolver::message () const
Definition at line 6 of file flp_solver.cpp.
Referenced by FLPSolver(), and TEST().
{
     return "Hello, World!";
   }
The documentation for this class was generated from the following files:
/datadisk/bbubu/repos/optasio/flp-tools/src/flp_solver.hpp
/datadisk/bbubu/repos/optasio/flp-tools/src/flp_solver.cpp