FLPTools Development: /datadisk/bbubu/repos/optasio/flp-tools/tests/rational_expr_test.cpp File Reference
rational_expr_test.cpp File Reference
#include <gtest/gtest.h>
#include "rational_expr.hpp"
#include "flp_solver.hpp"
Functions
TEST (RationalExprTest, DefaultConstructor)
TEST (RationalExprTest, LinearConstructor)
TEST (RationalExprTest, FullConstructor)
TEST (RationalExprTest, DivisionOfLinearExpr)
TEST (RationalExprTest, DivisionOfLinearExpr2)
Function Documentation
TEST() [1/5]
TEST (RationalExprTest , DefaultConstructor)
Definition at line 12 of file rational_expr_test.cpp.
References optasio::flp::RationalExpr::denominator, optasio::flp::RationalExpr::enumerator, optasio::flp::RationalExpr::is_linear(), and optasio::flp::RationalExpr::is_valid().
{
   // Act
   RationalExpr expr = RationalExpr();
   // Assert
   EXPECT_EQ(expr.enumerator.offset(), 1);
   EXPECT_EQ(expr.enumerator.terms().size(), 0);
   EXPECT_EQ(expr.denominator.offset(), 1);
   EXPECT_EQ(expr.denominator.terms().size(), 0);
   EXPECT_TRUE(expr.is_valid());
   EXPECT_TRUE(expr.is_linear());
 }
TEST() [2/5]
TEST (RationalExprTest , LinearConstructor)
Definition at line 24 of file rational_expr_test.cpp.
References optasio::flp::RationalExpr::denominator, optasio::flp::RationalExpr::enumerator, optasio::flp::RationalExpr::is_linear(), and optasio::flp::RationalExpr::is_valid().
{
   // Arrange
   FLPSolver solver = FLPSolver("TestSolver");
   LinearExpr x = solver.MakeVar(0.0, 1.0, false, "x");
   LinearExpr y = solver.MakeVar(0.0, 1.0, false, "y");
   LinearExpr enumerator = 2 * x + 42 * y;
   // Act
   RationalExpr expr = RationalExpr(enumerator);
   // Assert
   EXPECT_EQ(expr.enumerator.offset(), 0);
   EXPECT_EQ(expr.enumerator.terms().size(), 2);
   EXPECT_EQ(expr.denominator.offset(), 1);
   EXPECT_EQ(expr.denominator.terms().size(), 0);
   EXPECT_TRUE(expr.is_valid());
   EXPECT_TRUE(expr.is_linear());
 }
TEST() [3/5]
TEST (RationalExprTest , FullConstructor)
Definition at line 41 of file rational_expr_test.cpp.
References optasio::flp::RationalExpr::denominator, optasio::flp::RationalExpr::enumerator, optasio::flp::RationalExpr::is_linear(), and optasio::flp::RationalExpr::is_valid().
{
   // Arrange
   FLPSolver solver = FLPSolver("TestSolver");
   LinearExpr x = solver.MakeVar(0.0, 1.0, false, "x");
   LinearExpr y = solver.MakeVar(0.0, 1.0, false, "y");
   LinearExpr enumerator = 2 * x + 42 * y;
   LinearExpr denominator = 42 * x + 2 * y;
   // Act
   RationalExpr expr = RationalExpr(enumerator, denominator);
   // Assert
   EXPECT_EQ(expr.enumerator.offset(), 0);
   EXPECT_EQ(expr.enumerator.terms().size(), 2);
   EXPECT_EQ(expr.denominator.offset(), 0);
   EXPECT_EQ(expr.denominator.terms().size(), 2);
   EXPECT_TRUE(expr.is_valid());
   EXPECT_FALSE(expr.is_linear());
 }
TEST() [4/5]
TEST (RationalExprTest , DivisionOfLinearExpr)
Definition at line 59 of file rational_expr_test.cpp.
References optasio::flp::RationalExpr::denominator, optasio::flp::RationalExpr::enumerator, optasio::flp::RationalExpr::is_linear(), and optasio::flp::RationalExpr::is_valid().
{
   // Arrange
   FLPSolver solver = FLPSolver("TestSolver");
   LinearExpr x = solver.MakeVar(0.0, 1.0, false, "x");
   LinearExpr y = solver.MakeVar(0.0, 1.0, false, "y");
   // Act
   RationalExpr expr = (2 * x + 42 * y) / (42 * x + 2 * y);
   // Assert
   EXPECT_EQ(expr.enumerator.offset(), 0);
   EXPECT_EQ(expr.enumerator.terms().size(), 2);
   EXPECT_EQ(expr.denominator.offset(), 0);
   EXPECT_EQ(expr.denominator.terms().size(), 2);
   EXPECT_TRUE(expr.is_valid());
   EXPECT_FALSE(expr.is_linear());
 }
TEST() [5/5]
TEST (RationalExprTest , DivisionOfLinearExpr2)
Definition at line 75 of file rational_expr_test.cpp.
References optasio::flp::RationalExpr::denominator, optasio::flp::RationalExpr::enumerator, optasio::flp::RationalExpr::is_linear(), and optasio::flp::RationalExpr::is_valid().
{
   // Arrange
   FLPSolver solver = FLPSolver("TestSolver");
   LinearExpr x = solver.MakeVar(0.0, 1.0, false, "x");
   LinearExpr y = solver.MakeVar(0.0, 1.0, false, "y");
   // Act
   RationalExpr expr = 1 / (42 * x + 2 * y);
   // Assert
   EXPECT_EQ(expr.enumerator.offset(), 1);
   EXPECT_EQ(expr.enumerator.terms().size(), 0);
   EXPECT_EQ(expr.denominator.offset(), 0);
   EXPECT_EQ(expr.denominator.terms().size(), 2);
   EXPECT_TRUE(expr.is_valid());
   EXPECT_FALSE(expr.is_linear());
 }