FLPTools Development: optasio::flp Namespace Reference
optasio::flp Namespace Reference
Classes
class FLPSolver
class RationalExpr
Functions
bool linear_expr_is_nonzero (const LinearExpr &expr)
RationalExpr operator+ (RationalExpr lhs, double rhs)
RationalExpr operator+ (double lhs, RationalExpr rhs)
RationalExpr operator- (RationalExpr lhs, double rhs)
RationalExpr operator- (double lhs, RationalExpr rhs)
RationalExpr operator* (RationalExpr lhs, double rhs)
RationalExpr operator* (double lhs, RationalExpr rhs)
Function Documentation
linear_expr_is_nonzero()
bool optasio::flp::linear_expr_is_nonzero (const LinearExpr & expr)
Definition at line 8 of file rational_expr.cpp.
Referenced by optasio::flp::RationalExpr::is_valid().
{
   bool zero_offset = expr.offset() == 0;
   auto all_coeffs_are_zero = expr.terms().size() == 0;
   return !zero_offset || !all_coeffs_are_zero;
 }
operator*() [1/2]
RationalExpr optasio::flp::operator* (RationalExpr lhs, double rhs)
Definition at line 64 of file rational_expr.cpp.
Referenced by optasio::flp::RationalExpr::RationalExpr().
{
   return lhs *= rhs;
 }
operator*() [2/2]
RationalExpr optasio::flp::operator* (double lhs, RationalExpr rhs)
Definition at line 68 of file rational_expr.cpp.
{
   return rhs *= lhs;
 }
operator+() [1/2]
RationalExpr optasio::flp::operator+ (RationalExpr lhs, double rhs)
Definition at line 48 of file rational_expr.cpp.
Referenced by optasio::flp::RationalExpr::RationalExpr().
{
   return lhs += rhs;
 }
operator+() [2/2]
RationalExpr optasio::flp::operator+ (double lhs, RationalExpr rhs)
Definition at line 52 of file rational_expr.cpp.
{
   return rhs += lhs;
 }
operator-() [1/2]
RationalExpr optasio::flp::operator- (RationalExpr lhs, double rhs)
Definition at line 56 of file rational_expr.cpp.
{
   return lhs -= rhs;
 }
operator-() [2/2]
RationalExpr optasio::flp::operator- (double lhs, RationalExpr rhs)
Definition at line 60 of file rational_expr.cpp.
{
   return rhs -= lhs;
 }